### ISSUE TITLE
Part B  - Assignment Submission

### ISSUE THREAD

**Issue by katieenns** [katieenns/Dream-Team#1]
Below are the key point for Part-B submission.

1. Decompose your user stories into tasks.
2. Outline what features will be in Milestone 1.0 of your project.
3. Build the iterations (at most 2) that will compose your Milestone 1.0. Record the total days of work and the time it will take for your team to complete that work.
4. Make sure you have dealt with velocity before breaking into iterations.
5. Allocate tasks to each team member and record the allocation.
6. Create a burn down chart for monitoring your team’s progress.
7. Include evidence that you are meeting for periodic stand up meetings with your teammates, ideally at least twice a week.
8. Ensure that your development and testing environment is set up. Be sure to have some working functional (however rudimentary) and test code in your repository.

      - [X] Submit the repo address to canvas
      - [ ] Git clone
      - [ ] create a virtual environment
      - [ ] Include "requirementx.txt" file : pip freeze > requirementx.txt
      - [ ] Instructions in read me on how to run the project

**Comment by pankajcgu** [comment]
This is done.
