### ISSUE TITLE
Explore SQLite database to store data

### ISSUE THREAD

**Issue by katieenns** [katieenns/Dream-Team#4]
We are planning to store transactional data (like most widely search criteria and things like that) in backend database. We can use SQLite database to store transactional data. We will need to explore SQLite database and see how best we can configure and use it for our project.

Here is the sample on how to use SQLite database with Python web app.
https://www.digitalocean.com/community/tutorials/how-to-make-a-web-application-using-flask-in-python-3#step-2-creating-a-base-application

**Comment by programateer** [comment]
Import csv

New_additions = []

Filename = "DreamTeam_database.csv"

Fields = [
'ID',
'Query_Searched',
'Date_Accessed'
"Categories_Selected"
]

Data = []

print("Welcome to Database for the DreamTeam Application")

New_record = {
"ID": current_ID,
"Query_Searched": input(What was the Query Searched? >"),
"Date_Accessed": input(When was the Query Searched? >"),
"Categories_Selected": input(What Categories were activated? >")
}
New_additions.append(new_record)
Current_ID = Current_ID + 1
Print("-"*15)
Print("New Record was successfully inserted")

If len(new_additions) > 0:
	With open(filename, 'a') as csvfile:
		Writer = dsc.DictWriter(csvfile, fieldnames=fields)
		Writer.writeheader()
		For item in new_additions:
			Writer.writerow(item)
